global:
  identity:
    auth:
      issuer: http://keycloak:8090/realms/my-keycloak-as-oidc
      issuerBackendUrl: http://keycloak:8090/realms/my-keycloak-as-oidc
      tokenUrl: http://keycloak:8090/realms/my-keycloak-as-oidc/protocol/openid-connect/token
      jwksUrl: http://keycloak:8090/realms/my-keycloak-as-oidc/protocol/openid-connect/certs
      type: "GENERIC"
      identity:
        clientId: identity-api
        audience: identity-api
        existingSecret: 9VXzJC9Qe7R6RjPX2ptQbW5Etjk91EBY
#        initialClaimValue: ID from user (test/test)
        initialClaimValue: 62d55e73-7b92-4147-aaee-e493a6204944
        initialClaimName: sub
      zeebe:
        clientId: zeebe-api
        audience: zeebe-api
        existingSecret: R2lMlMLY30HKLl2JYxkhtSMxmgS7SZOf
#      optimize:
#        clientId: optimize-api
#        audience: optimize-api
#        existingSecret: PtvyX70elxVMcKuvPiaqSV4t0x8VcmU7
      operate:
        clientId: operate-api
        audience: operate-api
        existingSecret: DcEXp0uVAra3g10yIzmcCiPKai0TGwtN

operate:
  enabled: true

tasklist:
  enabled: false

optimize:
  contextPath: "/optimize"

connectors:
  enabled: false

webModeler:
  enabled: false

identityKeycloak:
  enabled: false #ext_kc

identityPostgresql:
  enabled: true

identity:
  fullURL: "http://localhost:8080"
  enabled: true
  keycloak:
    enabled: false
  env:
    - name: JAVA_TOOL_OPTIONS
      value: |
        -Dlogging.level.org.apache.http.impl.execchain.MainClientExec=DEBUG -Dlogging.level.org.apache.http.headers=DEBUG -Dlogging.level.org.apache.http.wire=DEBUG -Dlogging.level.io.camunda=TRACE -Dlogging.level.io.camunda.identity.sdk.impl.rest=TRACE

postgresql:
  enabled: false

prometheusServiceMonitor:
  enabled: true

zeebeGateway:
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  logLevel: debug
  env:
    - name: ZEEBE_GATEWAY_MONITORING_ENABLED
      value: "true"
    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
      value: none

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
  logLevel: debug
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "512m"
      memory: "2Gi"
  env:
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"

elasticsearch:
  master:
    replicaCount: 1
    persistence:
      size: 15Gi